title: SALLY的思维模型

theme: jekyll-theme-Hacker

description: >
一个人最重要的技能，在于他如何思考这个世界，他的思维方式和底层逻辑，决定了他的做事方式。所以我罗列了我思考的重要模型。人类永远需要在不断的模型迭代和更新中发展，这和机器学习的模型迭代是一样的，永远要在思想上活跃，行动上主动，才能让思想永远带领自己走向更远的地方。
终归，是一个问题解决者。只有解决问题的能力才是终极能力。
